# Generated by Django 4.2.1 on 2023-06-22 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название поля')),
                ('price', models.IntegerField(verbose_name='Цена поля на час')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефонный номер владельца')),
                ('lenght', models.IntegerField(default=0, verbose_name='Длина')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина')),
                ('adress', models.CharField(default='Ташкент', max_length=250, verbose_name='Адрес')),
                ('adress_url', models.URLField(default='https://yandex.uz/maps/10335/tashkent/?ll=69.279737%2C41.311151&z=12', max_length=300, verbose_name='Адрес URL')),
                ('adress_coordinates', models.CharField(default='41.311151, 69.279716', max_length=50, verbose_name='Кординаты адреса поля')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
                'ordering': ['-created_at', 'region'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название района')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='field/', verbose_name='Изображение')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.field')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея полей',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='booking.region', verbose_name='Район'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], max_length=10)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.field')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'unique_together': {('date', 'time', 'field')},
            },
        ),
    ]
